---
title: "2017 Jim Holland Summer Project"
author: "Ken Locey"
date: "July 12, 2017"
output: pdf_document
---

```{r}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/DistDecay/analyses/DistanceDecay")

# Load Soil Data
dat <- read.table("~/GitHub/SSRP_2017/colonydata.txt", sep = ",", header = TRUE)

soil.dat <- dat[dat$Type == 'soil', ]
skin.dat <- dat[dat$Type == 'skin', ]
```


```{r}
# Assign columns in data.frame to objects
# Calculate CFU's from colonies
soil.dat$rpf <- log2(soil.dat$Concentration + 1)
col.num <- soil.dat$Colonies
dil.factor <- soil.dat$Dilutions
soil.dat$cfu <- (col.num/0.1)/dil.factor # Calculate CFU from colony number
soil.dat$m.types <- soil.dat$Morphotypes
```


## Plot number of colony forming units (CFUs) 
```{r}
file <- paste("~/GitHub/SSRP_2017/CFU_vs_Rpf.png", sep="")
png(filename=file, width=5, height=5, units="in", res=600, pointsize=10)

plot.new()
par(mfrow=c(1, 1), mar = c(5,5,3,1), oma =c(0,0,2,0))

mod <- lm(cfu ~ rpf + I(rpf^2), data=soil.dat)
dat2 <- data.frame(cbind('rpf'=soil.dat$rpf, 'cfu'=predict(mod)))
dat2 <- dat2[order(dat2), ]
dat2 <- dat2[complete.cases(dat2), ]

r2 <- summary(mod)$r.squared
coefs <- summary(mod)$coefficients
summary(mod)

title <- paste("Colonies vs Rpf,\n r-square=", round(r2,2))
plot(soil.dat$rpf, soil.dat$cfu, main=title, 
  	xlab="Rpf concentration, log2(umol/L)", ylab="CFU",
  	cex.lab=1.5, cex.main=1.5, pch=19)


# predicts + interval
newx <- seq(min(soil.dat$rpf), max(soil.dat$rpf), len=100)
preds <- predict(mod, data.frame(rpf = newx), interval = "confidence") 

clr <- 'gray' #c(2,2,3,4,5) 
clr <- adjustcolor(clr, alpha.f = 0.3) 
polygon(c(rev(newx), newx), c(rev(preds[ ,3]), preds[ ,2]), col = clr, border = NA)

lines(dat2$rpf, dat2$cfu, col="red", lwd=2) # regression line (y~x) 
lines(lowess(soil.dat$rpf, soil.dat$cfu), col="blue", lwd=2) # lowess line (x,y)
points(soil.dat$rpf, soil.dat$cfu, pch=19)
dev.off()
```


## Plot morphotypes 
```{r}
file <- paste("~/GitHub/SSRP_2017/Morphotypes_vs_Rpf.png", sep="")
png(filename=file, width=5, height=5, units="in", res=600, pointsize=10)

mod <- lm(m.types ~ rpf, soil.dat)
dat2 <- data.frame(cbind('rpf'=soil.dat$rpf, 'mtypes'=predict(mod)))
dat2 <- dat2[order(dat2), ]
dat2 <- dat2[complete.cases(dat2), ]

r2 <- summary(mod)$r.squared
coefs <- summary(mod)$coefficients
summary(mod)

title <- paste("Morphotypes vs Rpf,\n r-square=", round(r2,2))
plot(soil.dat$rpf, soil.dat$m.types, main=title, 
  	xlab="Rpf concentration, log2(umol/L)", ylab="Number of morphotypes",
  	cex.lab=1.5, cex.main=1.5, pch=19)

# predicts + interval
newx <- seq(min(soil.dat$rpf), max(soil.dat$rpf), len=100)
preds <- predict(mod, data.frame(rpf = newx), interval = "confidence") 

clr <- 'gray' #c(2,2,3,4,5) 
clr <- adjustcolor(clr, alpha.f = 0.3) 
polygon(c(rev(newx), newx), c(rev(preds[ ,3]), preds[ ,2]), col = clr, border = NA)

lines(dat2$rpf, dat2$cfu, col="red", lwd=2) # regression line (y~x) 
lines(dat2$rpf, dat2$mtypes, col="red", lwd=2) # regression line (y~x) 
lines(lowess(soil.dat$rpf, soil.dat$m.types), col="blue", lwd=2) # lowess line (x,y)
points(soil.dat$rpf, soil.dat$m.types, pch=19)
dev.off()
```

# Skin Data
## Two-tailed T-test for di
```{r}
soil.dat <- soil.dat[soil.dat$Concentration > 0, ]
soil.dat <- soil.dat[soil.dat$Concentration < 1.7, ]

rpf <- log2(soil.dat$Concentration + 1)
col.num <- soil.dat$Colonies
dil.factor <- soil.dat$Dilutions
cfu <- (col.num/0.1)/dil.factor # Calculate CFU from colony number
soil.cfu <- log2(cfu)

skin.rpf <- log2(skin.dat$Concentration + 1)
skin.col.num <- skin.dat$Colonies
dil.factor <- skin.dat$Dilutions
skin.cfu <- (skin.col.num/0.1)/dil.factor # Calculate CFU from colony number
skin.cfu <- log2(skin.cfu)

t.test(skin.cfu, soil.cfu)

avg.skin <- mean(skin.cfu)
avg.soil <- mean(soil.cfu)
```